Repository gorrotowi/Nothing, pull requests merged in 2020-10, with the labels that each got.

#9 Moving fonts to new API usage
  Android/Nothing/app/src/main/java/com/gorro/nothing/NothingActivity.kt
  Android/Nothing/app/src/main/res/font/questrial_regular.otf
  Android/Nothing/app/src/main/res/layout/activity_nothing.xml
Labels: enhancement

#8 Adding a typealias...
  Android/Nothing/app/src/main/java/com/gorro/nothing/MonthAndDay.kt
  Android/Nothing/app/src/main/java/com/gorro/nothing/NothingActivity.kt
Labels: enhancement

#10 Moving pending texts to string resources
  Android/Nothing/app/src/main/java/com/gorro/nothing/NothingActivity.kt
  Android/Nothing/app/src/main/res/values-fr/strings.xml
  Android/Nothing/app/src/main/res/values-hi/strings.xml
  Android/Nothing/app/src/main/res/values-in/strings.xml
  Android/Nothing/app/src/main/res/values/strings.xml
Labels: enhancement

#11 Adding actions, this is just a first approach
  .github/workflows/android-feature.yml
  Android/Nothing/app/mock-google-services.json
  Android/Nothing/build.gradle
  Android/Nothing/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#12 Removing indexing macOS Files
  .gitignore
  Android/Nothing/.DS_Store
Labels: enhancement, hacktoberfest-accepted

#17 Fastlane initial setup
  Android/Nothing/Gemfile
  Android/Nothing/fastlane/Appfile
  Android/Nothing/fastlane/Fastfile
Labels: enhancement, hacktoberfest-accepted

#18 Adding the check lane to fastlane
  Android/Nothing/Gemfile.lock
  Android/Nothing/fastlane/Fastfile
Labels: enhancement

#13 enhacement/remove repeated code
  Android/Nothing/app/src/main/java/com/gorro/nothing/NothingActivity.kt
  Android/Nothing/app/src/main/java/com/gorro/nothing/utils/UiExt.kt
Labels: enhancement, hacktoberfest-accepted

#14 Fixing two of the multiple issues on the lint report
  Android/Nothing/app/build.gradle
  Android/Nothing/app/src/main/java/com/gorro/nothing/NothingActivity.kt
Labels: bug, enhancement, hacktoberfest-accepted

#15 Removing invalid styles
  Android/Nothing/app/src/main/res/values-v11/styles.xml
  Android/Nothing/app/src/main/res/values-v14/styles.xml
Labels: enhancement, hacktoberfest-accepted

#16 Changing for ellipsis character
  Android/Nothing/app/src/main/res/values-fr/strings.xml
  Android/Nothing/app/src/main/res/values-hi/strings.xml
  Android/Nothing/app/src/main/res/values-in/strings.xml
Labels: enhancement, hacktoberfest-accepted

#19 enhacement/detekt undocumented functions
  Android/Nothing/app/build.gradle
  Android/Nothing/app/quality.gradle
  Android/Nothing/app/src/main/java/com/gorro/nothing/MonthAndDay.kt
  Android/Nothing/build.gradle
  Android/Nothing/config/detekt/detekt.yml
  Android/Nothing/fastlane/Fastfile
  Android/Nothing/fastlane/README.md
  Android/Nothing/fastlane/report.xml
Labels: enhancement, hacktoberfest-accepted

#23 add first Nothing iOS version
  .gitignore
  iOS/Nothing.xcodeproj/project.pbxproj
  iOS/Nothing.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Nothing.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Nothing/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Nothing/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Nothing/Assets.xcassets/Contents.json
  iOS/Nothing/ContentView.swift
  iOS/Nothing/Info.plist
  iOS/Nothing/NothingApp.swift
  iOS/Nothing/Preview Content/Preview Assets.xcassets/Contents.json
  iOS/Nothing/fonts/questrial_regular.otf
  iOS/NothingTests/Info.plist
  iOS/NothingTests/NothingTests.swift
  iOS/NothingUITests/Info.plist
  iOS/NothingUITests/NothingUITests.swift
Labels: hacktoberfest-accepted

#24 Fixing some detekt issues and removing unused code
  Android/Nothing/app/src/main/java/com/gorro/nothing/NothingActivity.kt
  Android/Nothing/app/src/main/java/com/gorro/nothing/eggs/GlitchEffect.kt
  Android/Nothing/app/src/main/java/com/gorro/nothing/utils/UiExt.kt
Labels: bug, enhancement, hacktoberfest-accepted
